version = "3.11.1"

runner.dialect = scala213

maxColumn = 120

continuationIndent.callSite = 2

newlines {
  sometimesBeforeColonInMethodReturnType = false
}

align {
  arrowEnumeratorGenerator = false
  ifWhileOpenParen = false
  openParenCallSite = false
  openParenDefnSite = false

  tokens = ["%", "%%"]
}

docstrings {
  style = SpaceAsterisk
  wrap = no
}

rewrite {
  rules = [Imports, RedundantBraces]
  imports.sort = original
  redundantBraces.maxBreaks = 1
}
